[package]
name = "audio_player"
version = "0.1.0"
authors = ["drselump14"]
edition = "2018"

[lib]
name = "audio_player"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.29.1", features = ["nif_version_2_16"]}
lazy_static = "1.4"
rodio = "0.17.1"
