[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.arm-unknown-linux-gnueabihf]
image = "drselump14/audio_player_nif_builder:arm-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "drselump14/audio_player_nif_builder:aarch64-unknown-linux-gnu"
