[build.env]
passthrough = [
  "RUSTLER_NIF_VERSION"
]

[target.arm-unknown-linux-gnueabihf]
dockerfile = "images/Dockerfile.arm-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
dockerfile = "images/Dockerfile.aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
dockerfile = "images/Dockerfile.x86_64-unknown-linux-musl"
