FROM ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest

RUN dpkg --add-architecture arm64 && \
    apt-get update && \
    apt-get -y install libasound-dev libasound2-dev libssl-dev libpulse-dev libdbus-1-dev portaudio19-dev gcc-aarch64-linux-gnu
